# Generated by Django 5.0.3 on 2024-04-03 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "Non catégorisé"),
                            (1, "Revenus"),
                            (2, "Dépenses fixes"),
                            (3, "Salaire"),
                            (4, "Dividendes"),
                            (5, "Cotisations"),
                            (6, "Taxes et impôts"),
                            (7, "Autres"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=500)),
                ("date", models.DateField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("vat_percentage", models.IntegerField(default=0)),
                (
                    "vat_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "Non catégorisé"),
                            (1, "Revenus"),
                            (2, "Dépenses fixes"),
                            (3, "Salaire"),
                            (4, "Dividendes"),
                            (5, "Cotisations"),
                            (6, "Taxes et impôts"),
                            (7, "Autres"),
                        ]
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="transactions.subcategory",
                    ),
                ),
            ],
        ),
    ]
