# Generated by Django 5.0.3 on 2024-04-22 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="label",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="transactions.subcategory",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
